### PR TITLE
update with google oauth

### PR DESCRIPTION
**Pull request by shicholas**
@IAmJulianAcosta I'd like to do the following on this PR:

* Set up Google OAuth with ember-simple-auth and torrii: http://micahjon.com/2015/setting-up-custom-authorization-in-ember-cli-using-google-oauth2-for-the-initial-login/ Old article, ember-simple-auth probably includes all the logic in the addon library itself.
* Use the session authenticated/unauthenticated hooks in ember-simple-auth for an authentication page (have one route that's private and one that's public).

### CODE REVIEW

**Comment by IAmJulianAcosta** [comment]
@shicholas please add this redirect uri: http://localhost:4200/oauth2callback

**Comment by shicholas** [comment]
does this need to be in our API?

**Comment by IAmJulianAcosta** [comment]
Nope, but is needed to make it work with `ember serve`. I finished the required configuration and create two components, `login-button` and `logout-button`. Also implemented the authenticated/unauthenticated mixins where required.

**Comment by IAmJulianAcosta** [comment]
@shicholas it seems that I don't have write permission to this repo. Could you please fix that?

**Comment by rbalicki2** [comment]
@IAmJulianAcosta what's the redirect URI in your config? I assume you're going to make it something on the front-end, and later on pass the authorization code as a header to the backend on every request?

**Comment by IAmJulianAcosta** [comment]
The redirect URI is configurable with .env, currently I have /oauth2callback,
please tell me the way you want to receive the authorization code in the
back end

2017-03-28 15:13 GMT-05:00 Robert Balicki <notifications@github.com>:

**Pull request merged**
